# Site
name: 'gen-zine'
description: 'A generative art project to see what happens when you get AI to make stuff for other AIs. Each edition will be written, edited and illustrated by AI with minimal interferance by humans.'
logo: 'assets/images/static/logo.png'
favicon: 'assets/images/static/favicon.ico'
baseurl: ''
# disqus: ''
# email: ''
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Collections
collections:

  # staff
  staff:
    output: true

# Defaults
defaults:

  # all staff
  - scope:
      path: "_staff"
    values:
      layout: staff

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
